# Arrays

In [15]:
import numpy as np

In [17]:
a = np.array([[0,1,2,3], [4,5,6,7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [18]:
a.shape

(2, 4)

In [19]:
a[1,3]

7

In [20]:
a[1,2] = 8
a

array([[0, 1, 2, 3],
       [4, 5, 8, 7]])

In [21]:
a[0]

array([0, 1, 2, 3])

# Generating Random Numbers

In [22]:
import random

In [23]:
prob = random.random()
print(prob)

0.44014269047414767


In [24]:
number = random.randint(1,6)
print(number)

2


In [25]:
import numpy as np

In [26]:
np.random.randint(1,6,(4,6))

array([[3, 3, 1, 4, 4, 2],
       [3, 4, 3, 5, 4, 4],
       [2, 2, 1, 2, 5, 3],
       [3, 1, 4, 1, 3, 5]])

# Importing and Organizing Data in Python

In [27]:
import numpy as np
import pandas as pd

In [28]:
ser = pd.Series(np.random.random(5), name = "Column 01")

In [29]:
ser

0    0.142970
1    0.654607
2    0.557805
3    0.286759
4    0.484800
Name: Column 01, dtype: float64

In [30]:
ser[2]

0.5578046932629416

In [31]:
from pandas_datareader import data as wb

In [32]:
PG = wb.DataReader('PG', data_source='yahoo', start = '1995-1-1')

In [33]:
PG

High         Low        Open       Close      Volume  \
Date                                                                     
1995-01-03   15.625000   15.437500   15.468750   15.593750   3318400.0   
1995-01-04   15.656250   15.312500   15.531250   15.468750   2218800.0   
1995-01-05   15.437500   15.218750   15.375000   15.250000   2319600.0   
1995-01-06   15.406250   15.156250   15.156250   15.281250   3438000.0   
1995-01-09   15.406250   15.187500   15.343750   15.218750   1795200.0   
...                ...         ...         ...         ...         ...   
2021-09-17  146.279999  144.229996  144.369995  144.339996  18737400.0   
2021-09-20  144.850006  141.970001  144.220001  142.889999  10238700.0   
2021-09-21  144.529999  142.880005  142.979996  143.110001   6651300.0   
2021-09-22  144.350006  142.860001  143.820007  143.600006   6332500.0   
2021-09-23  144.684998  143.490005  144.059998  144.190002   5151412.0   

             Adj Close  
Date                    
1995-01-03    8.063840  
1995-01-04    7.999201  
1995-01-05    7.886079  
1995-01-06    7.902242  
1995-01-09    7.869921  
...                ...  
2021-09-17  144.339996  
2021-09-20  142.889999  
2021-09-21  143.110001  
2021-09-22  143.600006  
2021-09-23  144.190002  

[6730 rows x 6 columns]

In [34]:
PG.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 6730 entries, 1995-01-03 to 2021-09-23
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   High       6730 non-null   float64
 1   Low        6730 non-null   float64
 2   Open       6730 non-null   float64
 3   Close      6730 non-null   float64
 4   Volume     6730 non-null   float64
 5   Adj Close  6730 non-null   float64
dtypes: float64(6)
memory usage: 368.0 KB


In [35]:
PG.head()

High       Low      Open     Close     Volume  Adj Close
Date                                                                    
1995-01-03  15.62500  15.43750  15.46875  15.59375  3318400.0   8.063840
1995-01-04  15.65625  15.31250  15.53125  15.46875  2218800.0   7.999201
1995-01-05  15.43750  15.21875  15.37500  15.25000  2319600.0   7.886079
1995-01-06  15.40625  15.15625  15.15625  15.28125  3438000.0   7.902242
1995-01-09  15.40625  15.18750  15.34375  15.21875  1795200.0   7.869921

In [36]:
PG.tail()

High         Low        Open       Close      Volume  \
Date                                                                     
2021-09-17  146.279999  144.229996  144.369995  144.339996  18737400.0   
2021-09-20  144.850006  141.970001  144.220001  142.889999  10238700.0   
2021-09-21  144.529999  142.880005  142.979996  143.110001   6651300.0   
2021-09-22  144.350006  142.860001  143.820007  143.600006   6332500.0   
2021-09-23  144.684998  143.490005  144.059998  144.190002   5151412.0   

             Adj Close  
Date                    
2021-09-17  144.339996  
2021-09-20  142.889999  
2021-09-21  143.110001  
2021-09-22  143.600006  
2021-09-23  144.190002

In [37]:
tickers = ['PG', 'MSFT', 'T', 'F', 'GE']
new_data = pd.DataFrame()
for t in tickers:
    new_data[t] = wb.DataReader(t, data_source='yahoo', start='1995-1-1')['Adj Close']

In [38]:
new_data.tail()

PG        MSFT          T      F          GE
Date                                                            
2021-09-17  144.339996  299.869995  27.530001  13.55  100.470001
2021-09-20  142.889999  294.299988  27.209999  12.82   99.809998
2021-09-21  143.110001  294.799988  26.959999  12.77   96.820000
2021-09-22  143.600006  298.579987  27.010000  13.23   98.540001
2021-09-23  144.190002  299.559998  27.190001  13.71  102.959999

In [40]:
import quandl

In [41]:
mydata_01 = quandl.get("FRED/GDP")

In [42]:
mydata_01.tail()

Value
Date                 
2020-04-01  19477.444
2020-07-01  21138.574
2020-10-01  21477.597
2021-01-01  22038.226
2021-04-01  22731.369

In [43]:
mydata_01.head()

Value
Date               
1947-01-01  243.164
1947-04-01  245.968
1947-07-01  249.585
1947-10-01  259.745
1948-01-01  265.742

In [44]:
import pandas as pd

In [48]:
mydata_01.to_csv('C:/Users/Jared/Documents/GitHub/python_for_finance/example_01.csv')